language: python

python:
  - "2.7"

install:
  - pip install pyinstaller

script:
  - pyinstaller --onefile forticlientsslvpn_autoconnect.py

deploy:
  provider: releases
  api_key: $TOKEN
  file: "forticlientsslvpn_autoconnect"
  skip_cleanup: true
  on:
    tags: false
