language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch

install:
  - pip install pyinstaller

script:
  - pyinstaller --onefile forticlientsslvpn_autoconnect.py

deploy:
  provider: releases
  api_key: $TOKEN
  file: "forticlientsslvpn_autoconnect"
  skip_cleanup: true
  on:
    tags: false
